@extends('layouts.app')
@section('content')
@php($roleLabel = $user->isAdmin() ? 'Admin' : ($user->isDataEntry() ? 'Data Entry' : 'Viewer'))
<div class="page-heading">
    <div><p class="eyebrow"><span class="eyebrow-line"></span> {{ $roleLabel }} workspace</p><h1>{{ $user->isAdmin() ? 'Management dashboard' : ($user->isDataEntry() ? 'Data Entry Workspace' : 'Read-only Overview') }}</h1><p>{{ $user->isViewer() ? 'Explore live humanitarian data without changing records.' : 'A live view of your humanitarian operations.' }}</p></div>
    <div class="d-flex flex-wrap gap-2">
        @can('create-records')<a class="btn btn-primary" href="{{ route('families.create') }}">Add family <span aria-hidden="true">+</span></a>@endcan
        <a class="btn btn-outline-primary" href="{{ route('reports') }}">View reports <span aria-hidden="true">→</span></a>
    </div>
</div>
<div class="alert {{ $user->isViewer() ? 'alert-secondary' : 'alert-info' }} d-flex align-items-start gap-2" role="note"><span aria-hidden="true">{{ $user->isViewer() ? '◉' : '✦' }}</span><div><strong>{{ $user->isViewer() ? 'Read-only access.' : ($user->isAdmin() ? 'Administration access.' : 'Data entry access.') }}</strong> {{ $user->isViewer() ? 'You can search, review, and report on records. Write actions are restricted.' : ($user->isAdmin() ? 'You can manage users, records, exports, and audit history.' : 'You can create and update operational records. Destructive actions remain admin-only.') }}</div></div>
@if($user->isDataEntry())
<section class="card mb-4" aria-labelledby="entry-summary-title"><div class="card-body"><div class="d-flex justify-content-between align-items-center gap-3 flex-wrap"><div><p class="eyebrow mb-1">Today</p><h2 id="entry-summary-title" class="h5 mb-0">Your entry activity</h2></div><span class="badge text-bg-info">{{ $myEntriesToday }} records created or updated</span></div></div></section>
@endif
<section aria-labelledby="key-metrics-title"><h2 id="key-metrics-title" class="visually-hidden">Key metrics</h2><div class="row g-3 mb-4"><div class="col-sm-6 col-xl-3"><a class="stat-card d-block" href="{{ route('families.index') }}"><span class="stat-label">Total families</span><span class="stat-value d-block">{{ number_format($families) }}</span><span class="stat-icon" aria-hidden="true">◌</span></a></div><div class="col-sm-6 col-xl-3"><a class="stat-card d-block" href="{{ route('beneficiaries.index') }}"><span class="stat-label">Beneficiaries</span><span class="stat-value d-block">{{ number_format($beneficiaries) }}</span><span class="stat-icon" aria-hidden="true">♧</span></a></div><div class="col-sm-6 col-xl-3"><a class="stat-card d-block" href="{{ route('orphans.index') }}"><span class="stat-label">Orphan records</span><span class="stat-value d-block">{{ number_format($orphans) }}</span><span class="stat-icon" aria-hidden="true">♡</span></a></div><div class="col-sm-6 col-xl-3"><a class="stat-card d-block" href="{{ route('families.index', ['provider_status' => 'no_provider']) }}"><span class="stat-label">Families without provider</span><span class="stat-value d-block">{{ number_format($withoutProvider) }}</span><span class="stat-icon" aria-hidden="true">!</span></a></div></div></section>
<div class="row g-4 mb-4"><div class="col-sm-6 col-xl-3"><div class="card h-100"><div class="card-body"><p class="text-muted small mb-2">Aid this month</p><strong class="h3 mb-0">{{ number_format($aidThisMonth) }}</strong><p class="small text-muted mb-0 mt-2">Recorded distributions</p></div></div></div><div class="col-sm-6 col-xl-3"><div class="card h-100"><div class="card-body"><p class="text-muted small mb-2">Active sponsored orphans</p><strong class="h3 mb-0">{{ number_format($activeSponsoredOrphans) }}</strong><p class="small text-muted mb-0 mt-2">Active sponsorship records</p></div></div></div><div class="col-xl-6"><div class="card h-100"><div class="card-body"><div class="d-flex justify-content-between align-items-center mb-3"><h2 class="h6 mb-0">Families by region</h2><a class="small" href="{{ route('reports') }}">Full report</a></div>@forelse($familiesByRegion as $region)<div class="d-flex align-items-center gap-3 mb-2"><span class="small text-muted" style="width:110px">{{ $region->governorate }}</span><div class="progress flex-grow-1" style="height:8px" aria-label="{{ $region->governorate }} family share"><div class="progress-bar bg-info" style="width:{{ $families ? min(100, ($region->total / $families) * 100) : 0 }}%"></div></div><strong class="small">{{ $region->total }}</strong></div>@empty<div class="empty-state py-3"><p class="mb-0">No regional data yet.</p></div>@endforelse</div></div></div></div>
<div class="row g-4"><div class="col-lg-6"><div class="card h-100"><div class="card-header d-flex justify-content-between align-items-center"><h2 class="h6 mb-0">Recent families</h2><a class="small" href="{{ route('families.index') }}">View all</a></div><div class="list-group list-group-flush">@forelse($recentFamilies as $family)<a class="list-group-item list-group-item-action px-3 py-3" href="{{ route('families.show', $family) }}"><div class="d-flex justify-content-between gap-2"><strong>{{ $family->case_number }}</strong><span class="badge text-bg-light">{{ $family->governorate }}</span></div><span class="small text-muted">{{ $family->head_of_household_name }}</span></a>@empty<div class="empty-state"><div class="empty-state-icon">◌</div><p class="mb-0">No families have been recorded yet.</p></div>@endforelse</div></div></div><div class="col-lg-6"><div class="card h-100"><div class="card-header d-flex justify-content-between align-items-center"><h2 class="h6 mb-0">Recent aid distributions</h2><a class="small" href="{{ route('aid.index') }}">View all</a></div><div class="list-group list-group-flush">@forelse($recentAid as $aid)<a class="list-group-item list-group-item-action px-3 py-3" href="{{ route('aid.show', $aid) }}"><div class="d-flex justify-content-between gap-2"><strong>{{ $aid->aid_type }}</strong><span class="badge text-bg-light">{{ $aid->distribution_date?->format('d M Y') }}</span></div><span class="small text-muted">{{ $aid->family?->case_number ?? 'Unlinked case' }} · {{ $aid->reference_number ?? 'No reference' }}</span></a>@empty<div class="empty-state"><div class="empty-state-icon">▣</div><p class="mb-0">No aid distributions have been recorded yet.</p></div>@endforelse</div></div></div></div>
@endsection
