@extends('layouts.app', ['title' => __($distribution->exists ? 'aid.edit_title' : 'aid.add_title'), 'breadcrumb' => __($distribution->exists ? 'aid.edit_title' : 'aid.add_title')])
@section('content')
<h1>{{ __($distribution->exists ? 'aid.edit_title' : 'aid.add_title') }}</h1>
<form method="post" action="{{ $distribution->exists ? '/aid-distributions/'.$distribution->id : '/aid-distributions' }}">@csrf @if($distribution->exists) @method('PUT') @endif
<div class="row g-3"><div class="col-md-6"><label class="form-label" for="family_id">{{ __('aid.fields.family_id') }}</label><select class="form-select" id="family_id" name="family_id"><option value="">{{ __('aid.beneficiary_assistance') }}</option>@foreach($families as $family)<option value="{{ $family->id }}" @selected(old('family_id',$distribution->family_id)==$family->id)>{{ $family->case_number }} — {{ $family->head_of_household_name }}</option>@endforeach</select></div>
<div class="col-md-6"><label class="form-label">{{ __('aid.beneficiary_optional') }}</label><select class="form-select" name="beneficiary_id"><option value="">{{ __('aid.family_assistance') }}</option>@foreach($beneficiaries as $beneficiary)<option value="{{ $beneficiary->id }}" @selected(old('beneficiary_id',$distribution->beneficiary_id)==$beneficiary->id)>{{ $beneficiary->beneficiary_number }} — {{ $beneficiary->full_name }}</option>@endforeach</select></div>
<div class="col-md-4"><label class="form-label" for="aid_type">{{ __('aid.fields.aid_type') }}</label><select class="form-select" id="aid_type" name="aid_type" required><option value="" @selected(!old('aid_type',$distribution->aid_type))>{{ __('aid.fields.aid_type') }}</option>@foreach(\App\Http\Requests\AidDistributionRequest::AID_TYPES as $value)<option value="{{ $value }}" @selected(old('aid_type',$distribution->aid_type)===$value)>{{ __('statuses.aid.'.$value) }}</option>@endforeach</select></div>
<div class="col-md-4"><label class="form-label" for="distribution_date">{{ __('aid.fields.distribution_date') }}</label><input class="form-control" id="distribution_date" name="distribution_date" type="date" value="{{ old('distribution_date',$distribution->distribution_date?->format('Y-m-d')) }}" required></div>
@foreach(['quantity','amount','currency','provider_organization','reference_number'] as $field)<div class="col-md-4"><label class="form-label" for="{{ $field }}">{{ __('aid.fields.'.$field) }}</label><input class="form-control" id="{{ $field }}" name="{{ $field }}" type="text" value="{{ old($field,$distribution->$field) }}"></div>@endforeach
<div class="col-12"><label class="form-label">{{ __('aid.fields.notes') }}</label><textarea class="form-control" name="notes">{{ old('notes',$distribution->notes) }}</textarea></div></div>
@if($errors->any())<div class="alert alert-danger mt-3">{{ $errors->first() }}</div>@endif<button class="btn btn-primary mt-3">{{ __('aid.save') }}</button> <a class="btn btn-link" href="/aid-distributions">{{ __('aid.cancel') }}</a></form>
@endsection
