@extends('layouts.app', ['title' => __('aid.title'), 'breadcrumb' => __('aid.title')])
@section('content')
<div class="page-heading"><div><p class="eyebrow"><span class="eyebrow-line"></span> {{ __('aid.eyebrow') }}</p><h1>{{ __('aid.title') }}</h1><p>{{ __('aid.description') }}</p></div><div class="d-flex flex-wrap gap-2">@can('export-data')<a class="btn btn-outline-primary" href="{{ route('export', ['type' => 'aid'] + request()->query()) }}">{{ __('aid.export') }}</a>@endcan @can('create-records')<a class="btn btn-primary" href="/aid-distributions/create">{{ __('aid.record') }} <span aria-hidden="true">+</span></a>@endcan</div></div>
<form class="filter-panel row g-3 mb-4" method="get" aria-label="{{ __('aid.filter_label') }}"><div class="col-lg-8"><label class="form-label" for="aid-search">{{ __('aid.search') }}</label><input class="form-control" id="aid-search" name="search" value="{{ request('search') }}" placeholder="{{ __('aid.search_placeholder') }}"></div><div class="col-md-4 d-flex align-items-end gap-2"><button class="btn btn-primary flex-grow-1" type="submit">{{ __('aid.search') }}</button><a class="btn btn-outline-secondary" href="{{ route('aid.index') }}" aria-label="{{ __('aid.clear_filters') }}">×</a></div></form>
<div class="table-card card"><div class="table-responsive"><table class="table"><caption class="visually-hidden">{{ __('aid.table_caption') }}</caption><thead><tr><th scope="col">{{ __('aid.fields.distribution_date') }}</th><th scope="col">{{ __('aid.fields.family_id') }}</th><th scope="col">{{ __('aid.fields.beneficiary_id') }}</th><th scope="col">{{ __('aid.fields.aid_type') }}</th><th scope="col">{{ __('aid.fields.amount') }}</th><th scope="col">{{ __('aid.fields.reference_number') }}</th></tr></thead>
<tbody>@forelse($distributions as $distribution)
<tr><td><a href="{{ route('aid.show', $distribution) }}">{{ $distribution->distribution_date?->format('Y-m-d') }}</a></td><td>{{ $distribution->family?->case_number }}</td><td>{{ $distribution->beneficiary?->full_name ?? __('aid.family_level') }}</td><td>{{ \Illuminate\Support\Facades\Lang::has('statuses.aid.'.$distribution->aid_type) ? __('statuses.aid.'.$distribution->aid_type) : $distribution->aid_type }}</td><td>{{ $distribution->amount ?? '—' }} {{ $distribution->currency }}</td><td>{{ $distribution->reference_number ?? '—' }}</td></tr>
@empty<tr><td colspan="6"><div class="empty-state"><div class="empty-state-icon">▣</div><h2 class="h6">{{ __('aid.empty_title') }}</h2><p class="mb-0">{{ __('aid.empty_description') }}</p></div></td></tr>@endforelse</tbody></table></div></div><div class="mt-3">{{ $distributions->links() }}</div>
@endsection
