@extends('layouts.app', ['title' => __('families.title'), 'breadcrumb' => __('families.title')])
@section('content')
<div class="page-heading"><div><p class="eyebrow"><span class="eyebrow-line"></span> {{ __('families.eyebrow') }}</p><h1>{{ __('families.title') }}</h1><p>{{ __('families.description') }}</p></div><div class="d-flex flex-wrap gap-2"> @can('export-data')<a class="btn btn-outline-primary" href="{{ route('export', ['type' => 'families'] + request()->query()) }}">{{ __('families.export') }}</a>@endcan @can('create-records')<a class="btn btn-primary" href="/families/create">{{ __('families.add_title') }} <span aria-hidden="true">+</span></a>@endcan</div></div>
<form class="filter-panel row g-3 mb-4" method="get" aria-label="{{ __('families.filter_label') }}">
    <div class="col-lg-5"><label class="form-label" for="family-search">{{ __('families.search') }}</label><input class="form-control" id="family-search" name="search" value="{{ request('search') }}" placeholder="{{ __('families.search_placeholder') }}"></div>
    <div class="col-md-4 col-lg-3"><label class="form-label" for="family-region">{{ __('families.fields.governorate') }}</label><select class="form-select" id="family-region" name="governorate"><option value="">{{ __('families.all_governorates') }}</option>@foreach(['North Gaza','Gaza','Deir al-Balah','Khan Younis','Rafah'] as $value)<option value="{{ $value }}" @selected(request('governorate') === $value)>{{ __('statuses.governorate.'.$value) }}</option>@endforeach</select></div>
    <div class="col-md-4 col-lg-2"><label class="form-label" for="family-provider">{{ __('families.fields.provider_status') }}</label><select class="form-select" id="family-provider" name="provider_status"><option value="">{{ __('families.all_statuses') }}</option>@foreach(['has_provider','no_provider','deceased_provider','missing_provider','disabled_provider'] as $value)<option value="{{ $value }}" @selected(request('provider_status') === $value)>{{ __('statuses.provider.'.$value) }}</option>@endforeach</select></div>
    <div class="col-md-4 col-lg-2 d-flex align-items-end gap-2"><button class="btn btn-primary flex-grow-1" type="submit">{{ __('families.filter') }}</button><a class="btn btn-outline-secondary" href="{{ route('families.index') }}" aria-label="{{ __('families.clear_filters') }}">×</a></div>
</form>
<div class="table-card card"><div class="table-responsive"><table class="table"><caption class="visually-hidden">{{ __('families.table_caption') }}</caption><thead><tr><th scope="col">{{ __('families.fields.case_number') }}</th><th scope="col">{{ __('families.fields.head_of_household_name') }}</th><th scope="col">{{ __('families.fields.governorate') }}</th><th scope="col">{{ __('families.fields.area') }}</th><th scope="col">{{ __('families.fields.family_size') }}</th><th scope="col">{{ __('families.beneficiaries') }}</th><th scope="col">{{ __('families.fields.vulnerability_status') }}</th><th scope="col"><span class="visually-hidden">{{ __('families.actions') }}</span></th></tr></thead>
<tbody>@forelse($families as $family)
<tr><td><a href="{{ route('families.show', $family) }}">{{ $family->case_number }}</a></td><td>{{ $family->head_of_household_name }}</td><td>{{ \Illuminate\Support\Facades\Lang::has('statuses.governorate.'.$family->governorate) ? __('statuses.governorate.'.$family->governorate) : $family->governorate }}</td><td>{{ $family->area }}</td><td>{{ $family->family_size }}</td><td>{{ $family->beneficiaries_count }}</td><td><span class="badge text-bg-warning">{{ __('statuses.vulnerability.'.$family->vulnerability_status) }}</span></td><td>@can('edit-records')<a href="{{ route('families.edit', $family) }}">{{ __('families.edit') }}</a>@else<span class="text-muted small">{{ __('families.view') }}</span>@endcan</td></tr>
@empty<tr><td colspan="8"><div class="empty-state"><div class="empty-state-icon">◌</div><h2 class="h6">{{ __('families.empty_title') }}</h2><p class="mb-0">{{ __('families.empty_description') }}</p></div></td></tr>@endforelse</tbody></table></div></div><div class="mt-3">{{ $families->links() }}</div>
@endsection
