@extends('layouts.app', ['title' => __('beneficiaries.title'), 'breadcrumb' => __('beneficiaries.title')])
@section('content')
<div class="page-heading"><div><p class="eyebrow"><span class="eyebrow-line"></span> {{ __('beneficiaries.eyebrow') }}</p><h1>{{ __('beneficiaries.title') }}</h1><p>{{ __('beneficiaries.description') }}</p></div><div class="d-flex flex-wrap gap-2">@can('export-data')<a class="btn btn-outline-primary" href="{{ route('export', ['type' => 'beneficiaries'] + request()->query()) }}">{{ __('beneficiaries.export') }}</a>@endcan @can('create-records')<a class="btn btn-primary" href="/beneficiaries/create">{{ __('beneficiaries.add_title') }} <span aria-hidden="true">+</span></a>@endcan</div></div>
<form class="filter-panel row g-3 mb-4" method="get" aria-label="{{ __('beneficiaries.filter_label') }}">
    <div class="col-lg-6"><label class="form-label" for="beneficiary-search">{{ __('beneficiaries.search') }}</label><input class="form-control" id="beneficiary-search" name="search" value="{{ request('search') }}" placeholder="{{ __('beneficiaries.search_placeholder') }}"></div>
    <div class="col-md-4 col-lg-2"><label class="form-label" for="beneficiary-type">{{ __('beneficiaries.fields.beneficiary_type') }}</label><select class="form-select" id="beneficiary-type" name="beneficiary_type"><option value="">{{ __('beneficiaries.all_types') }}</option>@foreach(['child','adult','elderly','person_with_disability','caregiver','other'] as $value)<option value="{{ $value }}" @selected(request('beneficiary_type') === $value)>{{ __('statuses.beneficiary_type.'.$value) }}</option>@endforeach</select></div>
    <div class="col-md-4 col-lg-2"><label class="form-label" for="beneficiary-gender">{{ __('beneficiaries.fields.gender') }}</label><select class="form-select" id="beneficiary-gender" name="gender"><option value="">{{ __('beneficiaries.all') }}</option><option value="female" @selected(request('gender') === 'female')>{{ __('statuses.gender.female') }}</option><option value="male" @selected(request('gender') === 'male')>{{ __('statuses.gender.male') }}</option></select></div>
    <div class="col-md-4 col-lg-2 d-flex align-items-end gap-2"><button class="btn btn-primary flex-grow-1" type="submit">{{ __('beneficiaries.filter') }}</button><a class="btn btn-outline-secondary" href="{{ route('beneficiaries.index') }}" aria-label="{{ __('beneficiaries.clear_filters') }}">×</a></div>
</form>
<div class="table-card card"><div class="table-responsive"><table class="table"><caption class="visually-hidden">{{ __('beneficiaries.table_caption') }}</caption><thead><tr><th scope="col">{{ __('beneficiaries.fields.beneficiary_number') }}</th><th scope="col">{{ __('beneficiaries.fields.full_name') }}</th><th scope="col">{{ __('beneficiaries.fields.family_id') }}</th><th scope="col">{{ __('beneficiaries.fields.gender') }}</th><th scope="col">{{ __('beneficiaries.fields.age') }}</th><th scope="col">{{ __('beneficiaries.fields.beneficiary_type') }}</th><th scope="col">{{ __('beneficiaries.fields.disability_status') }}</th></tr></thead>
<tbody>@forelse($beneficiaries as $beneficiary)
<tr><td><a href="{{ route('beneficiaries.show', $beneficiary) }}">{{ $beneficiary->beneficiary_number }}</a></td><td>{{ $beneficiary->full_name }}</td><td>{{ $beneficiary->family?->case_number }}</td><td>{{ __('statuses.gender.'.$beneficiary->gender) }}</td><td>{{ $beneficiary->date_of_birth?->age }}</td><td><span class="badge text-bg-light">{{ __('statuses.beneficiary_type.'.$beneficiary->beneficiary_type) }}</span></td><td>{{ __($beneficiary->disability_status ? 'beneficiaries.yes' : 'beneficiaries.no') }}</td></tr>
@empty<tr><td colspan="7"><div class="empty-state"><div class="empty-state-icon">♧</div><h2 class="h6">{{ __('beneficiaries.empty_title') }}</h2><p class="mb-0">{{ __('beneficiaries.empty_description') }}</p></div></td></tr>@endforelse</tbody></table></div></div><div class="mt-3">{{ $beneficiaries->links() }}</div>
@endsection
