<?php
namespace App\Http\Controllers;
use App\Models\{Family,Beneficiary,Orphan,AidDistribution,AuditLog}; use Illuminate\Http\Request; use Illuminate\Support\Str;
class FamilyController extends Controller {
 public function index(Request $r){$q=Family::query(); if($s=$r->input('search'))$q->where(fn($x)=>$x->where('case_number','ilike',"%$s%")->orWhere('head_of_household_name','ilike',"%$s%")->orWhere('national_id','ilike',"%$s%")->orWhere('phone','ilike',"%$s%")); foreach(['governorate','area','provider_status','vulnerability_status'] as $f)if($r->filled($f))$q->where($f,$r->$f); return view('families.index',['families'=>$q->withCount('beneficiaries')->latest()->paginate(15)->withQueryString()]);}
 public function create(){return view('families.form',['family'=>new Family]);}
 public function store(Request $r){$d=$r->validate(['head_of_household_name'=>'required|string|max:255','national_id'=>'nullable|string|max:50','phone'=>'required|string|max:40','governorate'=>'required|string','area'=>'required|string','address'=>'nullable|string','family_size'=>'required|integer|min:1','provider_status'=>'required|in:has_provider,no_provider,deceased_provider,missing_provider,disabled_provider','vulnerability_status'=>'required|in:low,medium,high,critical','notes'=>'nullable|string']); $d['case_number']='FAM-'.now()->year.'-'.str_pad((string)(Family::withTrashed()->max('id')+1),4,'0',STR_PAD_LEFT);$d['created_by']=auth()->id();$f=Family::create($d); AuditLog::create(['user_id'=>auth()->id(),'action'=>'created','model_type'=>'Family','model_id'=>$f->id,'description'=>'Family created','new_values'=>$d,'ip_address'=>$r->ip()]); return redirect('/families')->with('status','Family created.');}
 public function show(Family $family){return view('families.show',['family'=>$family->load('beneficiaries','orphans.beneficiary','aidDistributions')]);}
 public function edit(Family $family){return view('families.form',compact('family'));}
 public function update(Request $r,Family $family){$d=$r->validate(['head_of_household_name'=>'required|string|max:255','national_id'=>'nullable|string|max:50','phone'=>'required|string|max:40','governorate'=>'required|string','area'=>'required|string','address'=>'nullable|string','family_size'=>'required|integer|min:1','provider_status'=>'required|in:has_provider,no_provider,deceased_provider,missing_provider,disabled_provider','vulnerability_status'=>'required|in:low,medium,high,critical','notes'=>'nullable|string']);$d['updated_by']=auth()->id();$old=$family->toArray();$family->update($d);AuditLog::create(['user_id'=>auth()->id(),'action'=>'updated','model_type'=>'Family','model_id'=>$family->id,'description'=>'Family updated','old_values'=>$old,'new_values'=>$d,'ip_address'=>$r->ip()]);return redirect('/families/'.$family->id)->with('status','Family updated.');}
 public function destroy(Family $family){abort_unless(auth()->user()->role==='admin',403);$family->delete();return redirect('/families')->with('status','Family archived.');}
}
