@extends('layouts.app', ['title' => __('orphans.title'), 'breadcrumb' => __('orphans.title')])
@section('content')
<div class="page-heading"><div><p class="eyebrow"><span class="eyebrow-line"></span> {{ __('orphans.eyebrow') }}</p><h1>{{ __('orphans.title') }}</h1><p>{{ __('orphans.description') }}</p></div><div class="d-flex flex-wrap gap-2">@can('export-data')<a class="btn btn-outline-primary" href="{{ route('export', ['type' => 'orphans'] + request()->query()) }}">{{ __('orphans.export') }}</a>@endcan @can('create-records')<a class="btn btn-primary" href="/orphans/create">{{ __('orphans.add_title') }} <span aria-hidden="true">+</span></a>@endcan</div></div>
<form class="filter-panel row g-3 mb-4" method="get" aria-label="{{ __('orphans.filter_label') }}"><div class="col-lg-8"><label class="form-label" for="orphan-search">{{ __('orphans.search') }}</label><input class="form-control" id="orphan-search" name="search" value="{{ request('search') }}" placeholder="{{ __('orphans.search_placeholder') }}"></div><div class="col-md-4 d-flex align-items-end gap-2"><button class="btn btn-primary flex-grow-1" type="submit">{{ __('orphans.search') }}</button><a class="btn btn-outline-secondary" href="{{ route('orphans.index') }}" aria-label="{{ __('orphans.clear_filters') }}">×</a></div></form>
<div class="table-card card"><div class="table-responsive"><table class="table"><caption class="visually-hidden">{{ __('orphans.table_caption') }}</caption><thead><tr><th scope="col">{{ __('orphans.fields.orphan_number') }}</th><th scope="col">{{ __('orphans.fields.beneficiary_id') }}</th><th scope="col">{{ __('orphans.fields.family_id') }}</th><th scope="col">{{ __('orphans.fields.orphan_status') }}</th><th scope="col">{{ __('orphans.fields.sponsorship_status') }}</th></tr></thead>
<tbody>@forelse($orphans as $orphan)
<tr><td><a href="{{ route('orphans.show', $orphan) }}">{{ $orphan->orphan_number }}</a></td><td>{{ $orphan->beneficiary?->full_name }}</td><td>{{ $orphan->family?->case_number }}</td><td><span class="badge text-bg-warning">{{ \Illuminate\Support\Facades\Lang::has('statuses.orphan.'.$orphan->orphan_status) ? __('statuses.orphan.'.$orphan->orphan_status) : $orphan->orphan_status }}</span></td><td>{{ \Illuminate\Support\Facades\Lang::has('statuses.sponsorship.'.$orphan->sponsorship_status) ? __('statuses.sponsorship.'.$orphan->sponsorship_status) : $orphan->sponsorship_status }}</td></tr>
@empty<tr><td colspan="5"><div class="empty-state"><div class="empty-state-icon">♡</div><h2 class="h6">{{ __('orphans.empty_title') }}</h2><p class="mb-0">{{ __('orphans.empty_description') }}</p></div></td></tr>@endforelse</tbody></table></div></div><div class="mt-3">{{ $orphans->links() }}</div>
@endsection
